AZURE_OPENAI_API_KEY = "783aebbbdafc446e809ff534fa2ac62b"
AZURE_OPENAI_ENDPOINT = "https://hulk-openai.openai.azure.com/"
AZURE_OPENAI_API_VERSION = "2023-03-15-preview"
deployment_name = "Verbatim-Synthesis"
AZURE_OPENAI_EMBEDDING_DEPLOYMENT = "Embedding-Model"